FROM python:3.11-slim
WORKDIR /code
COPY backend/lms_api/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY ../backend/lms_api .
CMD ["gunicorn", "lms.wsgi:application", "--bind", "0.0.0.0:5005"]





# FROM python:3.11-slim
# WORKDIR /code
# COPY ../backend/Lms_Api/requirements.txt ./
# RUN pip install --no-cache-dir -r requirements.txt
# COPY ../backend/Lms_Api .
# CMD ["gunicorn", "app.wsgi:application", "--bind", "0.0.0.0:8000"]
