# DevOps/Dockerfile.frontend
FROM node:18-alpine AS build
WORKDIR /app
COPY client-app/package*.json ./
RUN npm install
COPY client-app .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY DevOps/nginx/frontend.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
