# Generated by Django 5.1.5 on 2025-02-16 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_created_date_student_updated_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='studentId',
            new_name='student_id',
        ),
    ]
