# services:
# #dabase service ko lagi
#   # multiTenantDB:
#   #   image: mcr.microsoft.com/mssql/server:2022-latest
#   #   container_name: mssql_container
#   #   ports:
#   #   - 1433:1433
#   #   environment:
#   #   SA_PASSWORD: "test@123"
#   #   ACCEPT_EULA: "Y"
#   #   volumes:
#   #   - mssql_data:/var/opt/mssql

#   app:
#     image: lms:latest
#     # build:
#     # context: .
#     # dockerfile: Dockerfile
#     container_name: lms_app
#     ports:
#     # server mah expose garnu pari port : docker image bitra ko expose port
#     - 5295:8000
#     # environment:
#     # - ASPNETCORE_ENVIRONMENT=Development
#     # depends_on:
#     # - multiTenantDB
#   # app1:
#   #   image: ohc
#   #   container_name: ohc_app
#   #   ports:
#   #   - 7080:7080
#   #   environment:
#   #   - ASPNETCORE_ENVIRONMENT=Development
#   #   depends_on:
#   #   - multiTenantDB
#   # frontend:
#   #   image: erp_fimg
#   #   ports:
#   #   - 5173:5173
#   # volumes:
#   # mssql_data:

# version: '3.8'

# services:
#   db:
#     image: postgres:15
#     container_name: lms_postgres
#     restart: always
#     environment:
#       POSTGRES_DB: lms
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: cmos
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     ports:
#       - "5003:5432"

#   rabbitmq:
#     image: rabbitmq:3-management
#     container_name: lms_rabbitmq
#     ports:
#       - "5004:5672"  # AMQP
#       - "15673:15672"  # Management UI
#     environment:
#       RABBITMQ_DEFAULT_USER: guest
#       RABBITMQ_DEFAULT_PASS: guest

  
#   app:
#     image: lms:latest
#     container_name: lms_app
#     ports:
#       - "5005:8000"
#     depends_on:
#       - db
#     environment:
#       - DB_HOST=db
#       - DB_NAME=lms
#       - DB_USER=postgres
#       - DB_PASSWORD=cmos
#       - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672/
# volumes:
#   postgres_data: