# Generated by Django 5.1.5 on 2025-02-18 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0002_book_created_at_book_is_deleted_book_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('barcode', models.IntegerField(primary_key=True, serialize=False)),
                ('is_available', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.book')),
            ],
            options={
                'db_table': 'BookCopies',
                'indexes': [models.Index(fields=['book'], name='idx_bookcopies')],
            },
        ),
    ]
